== Robots

=== Control

Robots must be controlled autonomously. The use of a remote control, manual control, or passing information (by sensors, cables, wirelessly, etc.) to the robot is not allowed.

Robots must be started manually by the team captain.

Any pre-mapped type of dead reckoning (movements predefined based on known locations or placement of features in the field) is prohibited.

Robots must not damage any part of the field in any way.

=== Construction

Any robot kit or building blocks, either available on the market or built from raw hardware, may be used as long as the design and construction of the robot are primarily and substantially the original work of the students.

Teams are not permitted to use any commercially produced robot kits or sensors components that are specifically designed or marketed to complete any single major task of RoboCupJunior Rescue. Robots that do not comply will face immediate disqualification from the tournament.  If there is any doubt, teams should consult the Technical Committee (TC) prior to the competition.

For the safety of participants and spectators, only lasers of class 1 and 2 are allowed. This will be checked during inspection. Teams using lasers must be able to show the sensor’s data/information sheet.

Bluetooth Class 2, 3 and ZigBee communications are the only wireless communication types allowed in RoboCupJunior. Robots that have other types of wireless communications will need to be removed or disabled to prevent possible interference with other leagues competing in RoboCup. If the robot has equipment for other forms of wireless communication, the team must prove that they have been disabled. Robots that do not comply may face immediate disqualification from the tournament.

Robots may incur damage by falling off the field, making contact with another robot, or making contact with field elements.  The organizing committee cannot anticipate all potential situations where damage to the robot may occur. Teams should ensure that all active elements on a robot are properly protected with resistant materials. For example, electrical circuits must be protected from all human contact and direct contact with other robots and field elements.

When batteries are transported or moved, it is recommended that safety bags be used. Reasonable efforts should be made to ensure that robots avoid short circuits and chemical or air leaks.

=== Team

Each team must have only one robot on the field.

Each team must have between 2 and 4 members.

Each team member will need to explain their work and should have a specific technical role.

A student can be registered on only one team.

A team is only allowed to participate in one league: Rescue Line or Rescue Maze.

All team members must be the correct age as stated on the RCJ website: http://junior.robocup.org/robocupjunior-general-rules/.

Team members may compete in Rescue Line twice (2 international events). After competing in Rescue Line twice, they must move to another RoboCupJunior subleague.
A student will not be able to participate in the RoboCupJunior, Sydney 2019 if he/she has participated in any two of the following international competitions: RoboCupJunior, Hefei 2015 Rescue Line Secondary, RoboCupJunior, Leipzig Rescue Line Secondary, RoboCupJunior, Nagoya 2017 Rescue Line or RoboCupJunior, Montreal 2018 Rescue Line.

Mentors/parents are not allowed to be with the team members during the competition. The team members will have to self-govern themselves (without mentor's supervision or assistance) during the long stretch of hours at the competition.

=== Inspection

The robots will be scrutinized by a panel of referees before the start of the tournament and at other times during the competition to ensure that they meet the constraints described in these rules.

It is illegal to use a robot that is very similar to another team’s robot from a previous year or the current year.

It is the responsibility of the team to have their robot re-inspected, if their robot is modified at any time during the tournament.

Students will be asked to explain the operation of their robot in order to verify that construction and programming of the robot is their own work.

Students will be asked about their preparation efforts and may be requested to answer surveys and participate in video-taped interviews for research purposes.

All teams must complete a web form prior to the competition to allow judges to better prepare for the interviews.  Instructions on how to submit the form will be provided to the teams prior to the competition.

All teams have to submit their source code prior to the competition. The source code will not be shared with other teams without the team’s permission.

All teams must submit their engineering journal prior to the competition. The journals will not be shared with other teams without the team’s permission. However, it is highly recommended that teams publicly share their engineering journal. With the teams that indicate that their engineering journals could be shared publicly during the registration process, the journal alongside their poster presentation will be shared through the RoboCupJunior Forum so that other teams could learn from them.

=== Violations

Any violations of the inspection rules will prevent the offending robot from competing until modifications are made and the robot passes inspection.

Modifications must be made within the time schedule of the tournament and teams cannot delay tournament play while making modifications.

If a robot fails to meet all specifications (even with modifications), it will be disqualified from that round (but not from the tournament).

No mentor assistance is allowed during the competition. (See 6. Code of Conduct.)

Any violations of the rules may be penalized by disqualification from the tournament or the round or may result in a loss of points at the discretion of the referees, officials, organizing committee or general chairs.
